### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by MrStelk** [Udayskn/DP#2]
Do an introduction.
Provide an explanation on what each file does.

**Comment by Udayskn** [comment]
Ok bro good suggestion.
i will look into it

**Comment by MrStelk** [comment]
Do some changes to the readme. simply add a line about the use of algo in each file. We can close this issue.

**Comment by MrStelk** [comment]
issue still needs to be fixed.

**Comment by karthik-NvY** [comment]
good job

**Comment by MrStelk** [comment]
done
